---
menus:
    # Main menu and first sub-menu.
    wordpress_analytics:
        parent_slug: ''
        slug: wordpress_analytics
        display: Wordpress Analytics Settings
        display_menu: Wordpress Analytics
        func_display: wpan_display_general_menu_page
        capability: administrator
        display_submenu: General # Name displayed for the first sub-menu
        icon: dashicons-admin-generic
        position: 99
        sections:
            general_settings:
                id: general_settings
                name: general_settings_section
                display: General settings
                page: wpan_general_settings_page
                group: wpan_general_settings_option_group
                db_key: wpan:general_settings
                visible: true
                func_register: wpan_register_general_settings_fields
                func_display: wpan_display_general_settings_section
                display_section_title: false
                fields:
                    tracking_uid:
                        title: Google Analytics tracking ID
                        desc: >
                          To what Google Analytics property should the hits be sent to? The ID is usually in the
                          form UA-XXXXXX-Y. You can find the ID in the GA's admin, in the Tracking Info section of
                          the Property column.
                        default: ''
                        type: text
                        maxlength: 20
                    scroll_tracking: '0'
                    content_grouping: '0'
                    call_tracking: '0'
                    form_tracking: '0'
                    email_tracking: '0'
            content_grouping:
                id: content_grouping
                name: content_grouping_section
                display: Content grouping
                page: wpan_content_grouping_page
                group: wpan_content_grouping_option_group
                db_key: wpan:content_grouping
                visible: true
                func_register: wpan_register_content_grouping_fields
                func_display: wpan_display_content_grouping_section
                fields:
                    group_index_wordpress: '1'
                    group_index_woocommerce: '2'
                    group_index_blog: '3'
            scroll_tracking:
                id: scroll_tracking
                name: scroll_tracking_section
                display: Scroll tracking
                page: wpan_scroll_tracking_page
                group: wpan_scroll_tracking_option_group
                visible: true
                db_key: wpan:scroll_tracking
                func_register: wpan_register_scroll_tracking_fields
                func_display: wpan_display_scroll_tracking_section
                fields:
                    pixel_threshold: '300'
                    time_threshold: '60'
            call_tracking:
                id: call_tracking
                name: call_tracking_section
                display: Call tracking
                page: wpan_call_tracking_page
                group: wpan_call_tracking_option_group
                visible: true
                db_key: wpan:call_tracking
                func_register: wpan_register_call_tracking_fields
                func_display: wpan_display_call_tracking_section
                fields:
                    phone_regex_include_pattern: ''
                    phone_regex_exclude_pattern: ''
                    detect_phone_numbers: '1'
            hidden_settings:
                id: hidden_settings
                name: hidden_settings_section
                display: Hidden settings
                page: wpan_hidden_settings_page
                group: wpan_hidden_settings_option_group
                visible: false
                db_key: wpan:hidden_settings
                func_register: wpan_register_hidden_settings_fields
                func_display: wpan_display_hidden_settings_section
                fields:
                    enable_json_folder: '0'
    # Second sub-menu
    advanced_settings:
        parent_slug: wordpress_analytics
        slug: advanced_settings_menu
        display: Advanced Settings
        display_menu: Advanced
        func_display: wpan_display_advanced_menu_page
        capability: administrator
        sections:
            advanced_settings:
                id: advanced_settings
                name: advanced_settings_section
                display: Advanced settings
                page: wpan_advanced_settings_page
                group: wpan_advanced_settings_option_group
                visible: true
                db_key: wpan:advanced_settings
                func_register: wpan_register_advanced_settings_fields
                func_display: wpan_display_advanced_settings_section
                display_section_title: false
                fields:
                    network_mode: '0'
                    create_tracker: '1'
                    tracker_name: ga
                    cross_domain_support: '0'
                    enhanced_link_attribution: '0'
                    debug: '0'
            custom_code:
                id: custom_code
                name: custom_code_section
                display: Custom code
                page: wpan_custom_code_page
                group: wpan_custom_code_option_group
                visible: true
                db_key: wpan:custom_code
                func_register: wpan_register_custom_code_fields
                func_display: wpan_display_custom_code_section
                fields:
                    custom_code: ''