---
menus:
    # Main menu
    wordpress_analytics:
        parent_slug: ''
        slug: wordpress_analytics
        display: WordPress Analytics Settings
        display_menu: WordPress Analytics
        capability: administrator
        display_submenu: General # Name displayed for the first sub-menu
        position: 99
        type: tabbed
        desc: >
            WordPress Analytics settings. For the most recent version of the plugin, please visit
            the plugin's <a href="https://github.com/coccoinomane/wordpress-analytics">Github page</a>.
            For support, feel free to open an issue on Github.
        sections:
            general_settings:
                id: general_settings
                display: General settings
                display_section_title: true
                fields:
                    tracking_uid:
                        id: tracking_uid
                        title: Google Analytics tracking ID
                        desc: >
                            To what Google Analytics property should the hits be sent to? The ID is usually in the
                            form UA-XXXXXX-Y. You can find the ID in the GA's admin, in the Tracking Info section of
                            the Property column.
                        default: ''
                        type: text
                        attributes:
                            maxlength: 20
                    scroll_tracking:
                        id: scroll_tracking
                        title: Enable scroll tracking?
                        desc: >
                            Send events to Google Analytics based on the user scrolling activity on each page.
                        default: ''
                        type: checkbox
                    call_tracking:
                        id: call_tracking
                        title: Enable call tracking?
                        desc: >
                            Send an event to Google Analytics every time a user clicks on a phone number.
                        default: ''
                        type: checkbox
                    form_tracking:
                        id: form_tracking
                        title: Enable form tracking?
                        desc: >
                            Send an event to Google Analytics every time a user submits a form. For now it works
                            only for forms made with the Gravity Forms plugin. The events are sent using the 
                            measurement protocol with anonymized IPs; this means that the IP associated to the hit
                            will be, for example, 77.123.456.000 instead of 77.123.456.789, and that ad blockers
                            won't block the event.'
                        default: ''
                        type: checkbox
                    email_tracking:
                        id: email_tracking
                        title: Enable email tracking?
                        desc: >
                            Send an event to Google Analytics every time a user clicks on an email address.
                        default: ''
                        type: checkbox
                    content_grouping:
                        id: content_grouping
                        title: Enable content grouping?
                        desc: >
                            Group pageviews in Google Analytics using the <a href="https://support.google.com/analytics/answer/2853423">Content
                            Grouping</a> feature.
                        default: ''
                        type: checkbox
            content_grouping:
                id: content_grouping
                display: Content grouping
                display_section_title: true
                desc: >
                    <p>Settings for the content grouping functionality</p>
                fields:
                    group_index_wordpress:
                        id: group_index_wordpress
                        title: Group index for WordPress category
                        desc: >
                            Send the WordPress category to this group index in Google Analytics
                        default: ''
                        type: number
                        attributes:
                            min: 1
                            max: 1000
                    group_index_woocommerce:
                        id: group_index_woocommerce
                        title: Group index for Woocommerce product category
                        desc: >
                            Send the Woocommerce product category to this group index in Google Analytics
                        default: ''
                        type: number
                        attributes:
                            min: 1
                            max: 1000
                    group_index_blog:
                        id: group_index_blog
                        title: Group index for blog post category
                        desc: >
                            Send the blog post category to this group index in Google Analytics
                        default: ''
                        type: number
                        attributes:
                            min: 1
                            max: 1000
            scroll_tracking:
                id: scroll_tracking
                display: Scroll tracking
                display_section_title: true
                desc: >
                     <p>Settings for the scroll tracking functionality.</p>
                     <p>Parameters set here will be ignored if you have Javascript caching enabled.</p>
                fields:
                    pixel_threshold:
                        id: pixel_threshold
                        title: Pixels threshold for engagement
                        desc: >
                            Pixels the user needs to scroll before we consider him/her engaged.
                        default: 300
                        type: number
                        attributes:
                            min: 1
                            max: 10000
                    time_threshold:
                        id: time_threshold
                        title: Seconds required to read content
                        desc: >
                            Time in seconds the user needs to spend on the content before we consider it read
                        default: 60
                        type: number
                        attributes:
                            min: 1
                            max: 10000
                    custom_dimension_scroll_tracking:
                        id: custom_dimension_scroll_tracking
                        title: "Store user reading behavior in custom dimension:"
                        desc: >
                            Set to zero to disable the feature, otherwise specify the ID of the custom dimension
                            as a positive integer. The user reading behavior is either 'Reader' or 'Scanner' based on
                            whether they spent more or less time than the threshold to scroll until the end on the content.
                            The custom dimension is not set for users who didn't scroll until the end of the content.
                        default: 0
                        type: number
                        attributes:
                            min: 0
                            max: 1000
            call_tracking:
                id: call_tracking
                display: Call tracking
                display_section_title: true
                desc: >
                    <p>Settings for the call tracking functionality.</p>
                    <p>Parameters set here will be ignored if you have Javascript caching enabled.</p>
                fields:
                    phone_regex_include_pattern:
                        id: phone_regex_include_pattern
                        title: Phone pattern (include)
                        desc: >
                            Consider only phone numbers that match this pattern; leave blank to catch all clicks to 'tel:' links.
                        default: ''
                        type: text
                        attributes:
                            size: 30
                            maxlength: 200
                    phone_regex_exclude_pattern:
                        id: phone_regex_exclude_pattern
                        title: Phone pattern (exclude)
                        desc: >
                            Do not consider phone numbers that match this regex pattern; leave blank to catch all clicks to 'tel:' links.
                        default: ''
                        type: text
                        attributes:
                            size: 30
                            maxlength: 200
                    detect_phone_numbers:
                        id: detect_phone_numbers
                        title: Detect phone numbers automatically
                        desc: >
                            If set, automatically convert the pattern 'TEL: +39 06 123456' into a phone number link. Useful if you can't
                            input HTML in pages, ex. in a Visual Composer module.
                        default: '1'
                        type: checkbox
            hidden_settings:
                id: hidden_settings
                display: Hidden settings
                visible: false
                fields:
                    enable_json_folder:
                        id: enable_json_folder
                        title: Look for JSON meta boxes
                        desc: >
                            Include the meta boxes found in the 'acf' subfolder of the plugin folder; these must be in the 
                            <a href="http://www.advancedcustomfields.com/resources/local-json/">ACF JSON Format</a>.
                        default: ''
                        type: checkbox
    # Second sub-menu
    advanced_settings:
        parent_slug: wordpress_analytics
        slug: advanced_settings
        display: Advanced Settings
        display_menu: Advanced
        capability: administrator
        sections:
            advanced_settings:
                id: advanced_settings
                display: Advanced settings
                display_section_title: true
                fields:
                    network_mode:
                        id: network_mode
                        title: Network Mode
                        desc: >
                            Manage plugin options only at the network level, preventing site admins to change them.
                            IMPORTANT:: Until I find a way to use the Settings API to set options in the network admin (ex.
                            using http://wordpress.stackexchange.com/a/72503/86662), the plugin options will be set and read
                            from the main blog admin page rather than the network admin page.
                        default: ''
                        type: checkbox
                    create_tracker:
                        id: create_tracker
                        title: Create GA tacker?
                        desc: >
                            By default WordPress analytics will create a GA tracker named 'ga' that will be used to send
                            both events and pageviews to Google Analytics. If you uncheck this box, the plugin will
                            only send the events, without creating neither the tracker nor the pageview. If you do so,
                            make sure that a tracker is created (either manually or by another plugin) before WordPress
                            Analytics is loaded, and that a pageview is sent after that.
                        default: '1'
                        type: checkbox
                    tracker_name:
                        id: tracker_name
                        title: Name of the GA tracker to use
                        desc: >
                            By default we use 'ga' for the tracker name; change it to integrate with other
                            Analytics plugins. For example, to use WordPress Analytics together with plugins
                            such as 'WooCommerce Google Analytics Pro' and MonsterInsights, set this field
                            to __gaTracker and uncheck the 'Create Tracker' option.
                        default: ga
                        type: text
                        attributes:
                            maxlength: 50
                    enhanced_link_attribution:
                        id: enhanced_link_attribution
                        title: Enhanced Link Attribution
                        desc: >
                            Enable <a href="https://support.google.com/analytics/answer/2558867">Enhanced Link Attribution</a>. 
                            Remember to enable the option in the property settings inside Google Analytics as well.
                        default: '1'
                        type: checkbox
                    cross_domain_support:
                        id: cross_domain_support
                        title: Cross Domain Support
                        desc: >
                            Enable support for cross-domain tracking as described in <a href="https://developers.google.com/analytics/devguides/collection/analyticsjs/linker#bi-directional_cross-domain_tracking">
                            in Google's documentation</a>? This feature just loads the linker plugin; if you also need
                            to call the 'autoLink' function, use the 'Custom Code' feature in the Advanced Settings.
                        default: ''
                        type: checkbox
                    debug:
                        id: debug
                        title: Debug mode
                        desc: >
                            Log the plugin's activity to file. Two files will be written: debug.log in the plugin's folder and debug.log
                            in the wp-content folder. Furthermore, javascript-related activity will be shown in the browser's console.
                        default: ''
                        type: checkbox
            custom_code:
                id: custom_code
                display: Custom code
                display_section_title: true
                fields:
                    custom_code:
                        id: custom_code
                        title: Custom code
                        desc: >
                            Any code you write here will be included in all pages of your website just before the pageview is sent.
                            Remember to include the PHP opening & closing tags.
                        default: ''
                        type: code
                        attributes:
                            rows: 15
                            cols: 120
                            placeholder: Code written here will be injected in the head of the document. Remember the <?php tag to write PHP code.
